version: '3'

services:
  keeper:
    image: panfio/keeper:latest
    ports:
     - 8008:8088
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/postgres"

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: passpass
    ports: 
      - 5432:5432
